version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms14"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.1
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline.yml:/usr/share/logstash/pipeline.yml:ro
      - ./config/agent-install-pipeline:/usr/share/logstash/agent-install-pipeline.config:ro
      - ./config/site-eventprocessor-pipeline.config:/usr/share/logstash/site-eventprocessor-pipeline.config:ro
      - ./config/ui-rest-pipeline.config:/usr/share/logstash/ui-rest-pipeline.config:ro
      - ./extracted/:/data/logstash/logs/:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    volumes:
      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
